import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import React from "react";
import LicenseProvider from "./components/huge-icons-license";
import { hugeiconsLicense } from "@hugeicons/react-pro";

// import "./globals.css";
hugeiconsLicense(process.env.NEXT_PUBLIC_HUGEICONS_LICENSE || "");
const inter = Inter({ subsets: ["latin"] });

// const fmmFont = localFont({
//   src: [
//     { path: "../../public/font/Aeonik-Regular.otf", weight: "400" },
//     { path: "../../public/font/Aeonik-Medium.otf", weight: "500" },
//     { path: "../../public/font/Aeonik-Bold.otf", weight: "700" },
//   ],
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Careers Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <LicenseProvider>
        <body
        // className={inter.className}
        >
          {children}
        </body>
      </LicenseProvider>
    </html>
  );
}
